### ISSUE TITLE
divide by zero

### ISSUE THREAD

**Issue by eslam2010011** [thunderpunch/LadderLayoutManager#2]
![image](https://user-images.githubusercontent.com/21963428/45921054-64d3f700-beae-11e8-8c56-8cfd946ee7f9.png)

**Comment by Madina-S** [comment]
java.lang.ArithmeticException: divide by zero
        at uz.transaction.util.recycler_view_layout.LadderLayoutManager.fill(LadderLayoutManager.java:209)
        at uz.transaction.util.recycler_view_layout.LadderLayoutManager.onLayoutChildren(LadderLayoutManager.java:168)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:15761)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15761)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15761)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
        at android.view.View.layout(View.java:15761)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15761)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15761)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15761)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15761)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15761)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
        at android.view.View.layout(View.java:15761)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
        at android.view.View.layout(View.java:15761)
        at android.view.ViewGroup.layout(ViewGroup.java:5039)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2090)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1847)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1065)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5901)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:550)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:211)
